# Generated by Django 5.0.6 on 2024-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_rename_title_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='Video_link',
            field=models.TextField(),
        ),
    ]
