# Generated by Django 5.0.6 on 2024-06-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_alter_moves_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
