# Generated by Django 5.0.6 on 2024-06-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_moves_is_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moves',
            name='is_html',
        ),
    ]
