# Generated by Django 5.0.6 on 2024-06-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_remove_moves_is_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moves',
            old_name='difficult',
            new_name='Difficulty',
        ),
    ]
