# Generated by Django 5.0.6 on 2024-06-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_rename_difficult_moves_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
