# Generated by Django 5.0.6 on 2024-06-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0007_alter_category_id_alter_difficulty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
