# Generated by Django 5.0.6 on 2024-06-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0008_alter_category_id_alter_difficulty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moves',
            old_name='Difficulty',
            new_name='difficulty',
        ),
    ]
