# Generated by Django 5.0.6 on 2024-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0012_alter_moves_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='title_slug',
            field=models.SlugField(unique=True),
        ),
    ]
